### ISSUE TITLE
anybody share install command?

### ISSUE THREAD

**Issue by cemalefendi** [Chia-Network/block-metrics#40]
installed docker and builded. how can i solve this error.  i cjanged CHIA_ROOT  FOLDER but always give ame errror

sudo docker run -p 5000:5000 block-metrics
Error: chia config file not found at /root/.chia/mainnet/config/config.yaml. Ensure CHIA_ROOT is set to the correct chia root

**Comment by cmmarslender** [comment]
Just seeing this. Its expecting to find a CHIA_ROOT folder with a config.yaml as well as some certs necessary to connect to a full node (this needs to connect to a full node to get information about blocks).

Its a bit more involved to set this up in docker, though you can look at the k8s configs we have to get an idea of how to run this in k8s/docker https://github.com/Chia-Network/block-metrics/tree/main/k8s

Alternatively, you could just run the go app directly, if you have a system with a full node running already. On that system, just `go run main.go serve` (or go build, and run `block-metrics serve`

It also is going to want a mysql database to write the block information to so that queries can be run to get the data back over the time ranges

**Comment by cmmarslender** [comment]
I added a PR with a readme in this PR https://github.com/Chia-Network/block-metrics/pull/44

**Comment by cmmarslender** [comment]
On the off chance that after reading that readme, this is not the repo you were looking for, you might look at https://github.com/Chia-Network/chia-exporter - its a prometheus exporter for blockchain/farmer/etc metrics
